{"name": "test01", "status": "broken", "statusDetails": {"message": "FileNotFoundError: [Errno 2] No such file or directory: 'E:\\\\config\\\\oxurl.yaml'", "trace": "@pytest.fixture()\n    def read_yaml():\n>       with open(path +r'\\oxurl.yaml', 'r', encoding='utf-8') as file:\nE       FileNotFoundError: [Errno 2] No such file or directory: 'E:\\\\config\\\\oxurl.yaml'\n\nconftest.py:13: FileNotFoundError"}, "start": 1589787232892, "stop": 1589787232892, "uuid": "1c2bd62e-4bd4-4a0e-8a69-2da843a976da", "historyId": "2909e1abfa0d7696865cd420ee356d2c", "testCaseId": "ed516452ccf4bb7e3c47659b8648e71f", "fullName": "casepage.test_pytest.Testcase#test01", "labels": [{"name": "tag", "value": "g1"}, {"name": "parentSuite", "value": "casepage"}, {"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "Testcase"}, {"name": "host", "value": "YQZ9SLS9R78ZP4U"}, {"name": "thread", "value": "5136-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "casepage.test_pytest"}]}